apiVersion: batch/v1
kind: Job
metadata:
  name: mpi-weather-job
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: mpi-weather
        image: ubuntu:20.04
        command: ["/bin/bash", "-c"]
        args:
        - |
          apt-get update && \
          DEBIAN_FRONTEND=noninteractive apt-get install -y python3 python3-pip mpich && \
          pip3 install mpi4py numpy psutil && \
          cp /mpi-code/weather_mpi.py /weather_mpi.py && \
          chmod +x /weather_mpi.py && \
          mpiexec -n 4 python3 /weather_mpi.py
        volumeMounts:
        - name: mpi-code
          mountPath: /mpi-code
        - name: hostfile
          mountPath: /etc/hostfile
      restartPolicy: Never
      volumes:
      - name: mpi-code
        configMap:
          name: mpi-weather-code
      - name: hostfile
        configMap:
          name: mpi-hostfile